#!/bin/bash
#
#Reisilt tagasi tuleku arvutamine
#
#Skripti algus
#
echo "Pyhapaev-0, Esmaspaev-1, Teisipaev-2, Kolmapaev-3, Neljapaev-4, Reede-5, Laupaev-6"
echo -n "Sisesta millal sõidad ära:"
read reisi_algus
echo -n "Sisesta reisi oopaevade arv:"
read paevad
ylejaanud_reisi_paevad=$(($paevad%7))
tagasi=$(($reisi_algus+$ylejaanud_reisi_paevad))
echo "Tagasi jouad paeval number $tagasi"
